services:
  - docker

before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_8fd98965e4fe_key 
    -iv $encrypted_8fd98965e4fe_iv 
    -in github_deploy_key_travis.enc 
    -out github_deploy_key_travis 
    -d
  - chmod 600 github_deploy_key_travis
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key_travis

script: 
  - echo "$docker_ci_pwd" | docker login -u "$docker_ci_user" --password-stdin
  - docker build . 
  - docker build -t rust-cov .
  - docker images
