language: minimal

services:
  - docker

stages:
  - build
  - name: deploy
    if: branch = master

job:
  include:
    - stage: build
      before_install:
        - >-
          openssl aes-256-cbc 
          -K $encrypted_8fd98965e4fe_key 
          -iv $encrypted_8fd98965e4fe_iv 
          -in github_deploy_key_travis.enc 
          -out github_deploy_key_travis 
          -d
        - chmod 600 github_deploy_key_travis
        - eval $(ssh-agent -s)
        - ssh-add github_deploy_key_travis
      script: 
        - echo "$docker_ci_pwd" | docker login -u "$docker_ci_user" --password-stdin
        - docker build -t bouvrais/rust-cov:$TRAVIS_COMMIT .
        - docker images
        - docker push bouvrais/rust-cov:$TRAVIS_COMMIT
    - stage: deploy
        - echo "$docker_ci_pwd" | docker login -u "$docker_ci_user" --password-stdin
        - docker pull bouvrais/rust-cov:$TRAVIS_COMMIT
        - docker tag bouvrais/rust-cov:$TRAVIS_COMMIT bouvrais/rust-cov:`cat last`
        - docker tag bouvrais/rust-cov:$TRAVIS_COMMIT bouvrais/rust-cov:latest
        - docker push bouvrais/rust-cov:`cat last`
        - docker push bouvrais/rust-cov:latest
